spring.datasource.url=jdbc:mariadb://localhost:3306/anotaai?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=anotaai
spring.datasource.password=261322

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Aumentar os limites do Tomcat para engolir imagens do Chat e Publicações em Base64
server.tomcat.max-http-form-post-size=20MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB